# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import csv
def datarater(apps,schema_editor):
    Rater = apps.get_model('moviereviewapp','Rator')
    with open('/Users/chucklapress/tiy-projects/movie_data/ml-100k/u.user', 'r') as infile:
        data = csv.reader(infile, delimiter='|')
        for row in data:
            Rater.object.create(user_id=row[0], age=row[1], gender=row[2], occupation=row[3], zipcode=row[4])


def datamovie(apps,schema_editor):
    Movie = apps.get_model('moviereviewapp','Movie')
    with open('/Users/chucklapress/tiy-projects/movie_data/ml-100k/u.user', 'r') as inFile:
        data = csv.reader(inFile,encoding='latin1',delimiter='\t')
        for row in data:
            Movie.object.create(movie_id=row[0], movie_title=row[1], release_date=row[2],video_release_date=row[3], IMBD_URL=row[4], unknown=row[5], actiom=row[6], adventure=row[7], animation=row[8], childrens=row[9], comedy=row[10], crime=row[11], documentary=row[12], drama=row[13], fantasy=row[14], film_noir=row[15], horror=row[16], musical=row[17], mystery=row[18], romance=row[19], sci_fi=row[20], thriller=row[21], war=row[22], western=row[23])

def datareview(apps,schema_editor):
    Review =apps.get_model('moviereviewapp','Review')
    with open('/Users/chucklapress/tiy-projects/movie_data/ml-100k/u.user', 'r') as infile:
        data = csv.reader(infile,encoding='latin1',delimiter='\t')
        for row in data:
            Review.object.create(user_id=row[0], movie_id=row[1], rating=row[2], timestamp=row[3])






class Migration(migrations.Migration):

    dependencies = [
        ('moviereviewapp', '0001_initial'),

    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('movie_title', models.IntegerField()),
                ('release_date', models.CharField(max_length=20)),
                ('video_release_date', models.CharField(max_length=20)),
                ('IMBd_URL', models.CharField(max_length=20)),
                ('unknown', models.CharField(max_length=30)),
                ('action', models.IntegerField()),
                ('adventure', models.IntegerField()),
                ('animation', models.IntegerField()),
                ('childrens', models.IntegerField()),
                ('comedy', models.IntegerField()),
                ('crime', models.IntegerField()),
                ('documentary', models.IntegerField()),
                ('drama', models.IntegerField()),
                ('fantasy', models.IntegerField()),
                ('film_noir', models.IntegerField()),
                ('horror', models.IntegerField()),
                ('musical', models.IntegerField()),
                ('mystery', models.IntegerField()),
                ('romance', models.IntegerField()),
                ('sci_fi', models.IntegerField()),
                ('thriller', models.IntegerField()),
                ('war', models.IntegerField()),
                ('western', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('timestamp', models.IntegerField()),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviereviewapp.Movie')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviereviewapp.Rater')),
            ],
        ),
    ]
